### ISSUE TITLE
You stole my code.

### ISSUE THREAD

**Issue by CybernetiX-S3C** [zanyarjamal/IP-Locator#4]
[Original IP-LOCATOR](https://Cybernetix-S3C.github.io/main/ip-locator)

[Snap Store original IP-LOCATOR](https://snapcraft.io/IP-Locator/)

https://github.com/CybernetiX-S3C/Ip-locator

**Comment by hani9208** [comment]
i can not install ip- locator can you helping me i try many times .am just beging use it and use kali

**Comment by CybernetiX-S3C** [comment]
It is direct run only. My originals have instructions
